baseurl = "http://www.mq-patrol.com/"
languageCode = "en-AU"
title = "MQ-Patrol.com"

pluralizelisttitles = "false"
preserveTaxonomyNames = "true"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

publishDir = ".gh-pages/"

[params]

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
    
[[menu.main]]
    name = "Wiki"
    weight = 2
    url = "/wiki/"
    
[[menu.main]]
    name = "Service Manuals"
    weight = 3
    url = "/service-manuals/"
